"""Общие фикстуры для TDD release-freeze / version-source-of-truth.

Строим временные репозитории в tmp_path: 6 desktop-источников + pubspec +
release-status.json + dist-ассеты + release-manifest.json. Настоящий git-репо
через subprocess (init/commit) допустим в тестах — guard read-only на git.

Реализация (scripts/release/version.py + guard в publish_release) ещё не
написана: тесты, использующие эти хелперы, обязаны падать сегодня (red-first).
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

# Канонический VERSION блока (spec 2026-07-17, owner-gate).
VERSION = "1.0.0-rc3"
# Тестовый expected-signer thumbprint (40-hex, SHA-1 cert thumbprint form).
SIGNER_THUMBPRINT = "A1B2C3D4E5F6A1B2C3D4E5F6A1B2C3D4E5F6A1B2"
_UNSET = object()  # sentinel: "thumbprint not specified" (default it for distributable)
BURNED_VERSIONS = ["1.0.0-rc1", "1.0.0-rc2"]
# Реальный frozen rc2 (release-status.json) — не совпадёт с крошечными тест-байтами.
FROZEN_RC2_SHA = "E0A0B2A395DD5C1D6A42ED82E235AD6A7CB9768409D71F70ED0CC91E5C5B5C1A"

DESKTOP_KEYS = ("pyproject", "kernel", "cargo_toml", "cargo_lock", "tauri", "iss", "ui")


# ── хеши ──────────────────────────────────────────────────────────────────
def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


# ── git ──────────────────────────────────────────────────────────────────
def git(repo: Path, *args: str, env: dict | None = None) -> subprocess.CompletedProcess:
    """Запустить git в repo; поднять с stderr при ненулевом коде."""
    full_env = {**os.environ, **(env or {})}
    proc = subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, env=full_env
    )
    if proc.returncode != 0:
        raise RuntimeError(f"git {args} failed: {proc.stderr}")
    return proc


def init_git(repo: Path) -> None:
    """Детерминированный репо: autocrlf off (байты стабильны), подпись off."""
    git(repo, "init")
    git(repo, "config", "user.email", "tdd@kali.test")
    git(repo, "config", "user.name", "TDD")
    git(repo, "config", "commit.gpgsign", "false")
    git(repo, "config", "core.autocrlf", "false")


def commit_all(repo: Path, msg: str = "baseline", date: str | None = None) -> None:
    """add -A + commit; date (ISO с оффсетом) фиксирует committer/author-эпоху."""
    git(repo, "add", "-A")
    env = None
    if date is not None:
        env = {"GIT_COMMITTER_DATE": date, "GIT_AUTHOR_DATE": date}
    git(repo, "commit", "-m", msg, env=env)


def head_sha(repo: Path) -> str:
    return git(repo, "rev-parse", "HEAD").stdout.strip()


def committer_epoch(repo: Path) -> float:
    """UTC-epoch committer-даты HEAD (%cI → offset-aware → timestamp)."""
    iso = git(repo, "log", "-1", "--format=%cI").stdout.strip()
    return datetime.fromisoformat(iso).timestamp()


# ── writers: desktop-источники ─────────────────────────────────────────────
def write_pyproject(repo: Path, version: str, decoy: bool = False,
                    dynamic: bool = False) -> None:
    if dynamic:
        body = '[project]\nname = "kali"\ndynamic = ["version"]\n'
    else:
        decoy_tbl = '\n[tool.decoy]\nversion = "9.9.9"\n' if decoy else ""
        body = f'[project]\nname = "kali"\nversion = "{version}"\n{decoy_tbl}'
    (repo / "pyproject.toml").write_text(body, encoding="utf-8")


def write_kernel(repo: Path, version: str | None, style: str = "double") -> None:
    """style: double|single|annotated|missing."""
    (repo / "kernel").mkdir(exist_ok=True)
    if style == "missing":
        line = "# no version here\n"
    elif style == "single":
        line = f"__version__ = '{version}'\n"
    elif style == "annotated":
        line = f'__version__: str = "{version}"\n'
    else:
        line = f'__version__ = "{version}"\n'
    (repo / "kernel" / "__init__.py").write_text(
        f'"""KALI kernel."""\n{line}', encoding="utf-8"
    )


def write_cargo_toml(repo: Path, version: str) -> None:
    (repo / "src-tauri").mkdir(exist_ok=True)
    (repo / "src-tauri" / "Cargo.toml").write_text(
        f'[package]\nname = "kali-desktop"\nversion = "{version}"\nedition = "2021"\n',
        encoding="utf-8",
    )


def write_cargo_lock(repo: Path, version: str, decoy_ver: str = "1.0.0-rc2") -> None:
    """Ловушка: `version = 4` (формат) + decoy-пакет foo + блок kali-desktop."""
    (repo / "src-tauri").mkdir(exist_ok=True)
    text = (
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n"
        "\n"
        "[[package]]\n"
        'name = "foo"\n'
        f'version = "{decoy_ver}"\n'
        "\n"
        "[[package]]\n"
        'name = "kali-desktop"\n'
        f'version = "{version}"\n'
        "dependencies = [\n"
        ' "anyhow",\n'
        "]\n"
        "\n"
        "[[package]]\n"
        'name = "anyhow"\n'
        'version = "1.0.86"\n'
    )
    (repo / "src-tauri" / "Cargo.lock").write_text(text, encoding="utf-8")


def write_tauri(repo: Path, version: str) -> None:
    (repo / "src-tauri").mkdir(exist_ok=True)
    (repo / "src-tauri" / "tauri.conf.json").write_text(
        json.dumps({"productName": "KALI", "version": version}, indent=2),
        encoding="utf-8",
    )


def write_iss(repo: Path, version: str) -> None:
    """Как реальный файл: stale-версия в header/Output-комментах + #define."""
    (repo / "scripts").mkdir(exist_ok=True)
    text = (
        f"; KALI Premium {version} — Inno Setup script\n"
        "; Supports >4GB installers (unlike 32-bit 7z SFX).\n"
        "; Compile: iscc scripts\\installer_premium.iss\n"
        f"; Output: dist_premium\\KALI-Premium-Setup-{version}.exe\n"
        "\n"
        '#define AppName "KALI Premium"\n'
        f'#define AppVersion "{version}"\n'
        '#define AppExe "kali-desktop.exe"\n'
        "\n"
        "[Setup]\n"
        "AppName={#AppName}\n"
        "AppVersion={#AppVersion}\n"
        "OutputBaseFilename=KALI-Premium-Setup-{#AppVersion}\n"
    )
    (repo / "scripts" / "installer_premium.iss").write_text(text, encoding="utf-8")


def write_ui(repo: Path, version: str, decoy: bool = False) -> None:
    """ui/package.json: top-level version первым; decoy — вложенный "version" ПОСЛЕ.

    Явный текст (не json.dumps): фиксирует порядок ключей и позволяет тесту
    доказать, что sync не переформатирует остальной JSON.
    """
    (repo / "ui").mkdir(exist_ok=True)
    lines = [
        "{",
        '  "name": "kali-ui",',
        '  "private": true,',
        f'  "version": "{version}",',
        '  "type": "module",',
    ]
    if decoy:
        lines.append('  "engines": { "version": "9.9.9" },')  # вложенный decoy ПОСЛЕ top-level
    lines.append('  "dependencies": {}')
    lines.append("}")
    (repo / "ui" / "package.json").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_pubspec(repo: Path, mobile_version: str = "0.1.0+1",
                  decoy: bool = False) -> None:
    (repo / "mobile").mkdir(exist_ok=True)
    decoy_block = ""
    if decoy:
        decoy_block = "dependencies:\n  foo:\n    version: 9.9.9\n"
    (repo / "mobile" / "pubspec.yaml").write_text(
        f"name: kali_mobile\nversion: {mobile_version}\n\n{decoy_block}",
        encoding="utf-8",
    )


def write_version_file(repo: Path, raw: bytes) -> None:
    (repo / "VERSION").write_bytes(raw)


def write_all_desktop(repo: Path, version: str, mobile_version: str = "0.1.0+1") -> None:
    """Все 6 desktop-источников + pubspec на одной version (synced)."""
    write_pyproject(repo, version)
    write_kernel(repo, version)
    write_cargo_toml(repo, version)
    write_cargo_lock(repo, version)
    write_tauri(repo, version)
    write_iss(repo, version)
    write_ui(repo, version)
    write_pubspec(repo, mobile_version)


# ── release-status / dist / manifest ───────────────────────────────────────
def write_status(repo: Path, *, distributable=True, frozen=None,
                 burned=None, canonical: str | None = None,
                 drop_frozen: bool = False, raw: str | None = None,
                 expected_signer_thumbprint=_UNSET) -> None:
    if raw is not None:
        (repo / "release-status.json").write_text(raw, encoding="utf-8")
        return
    data: dict = {
        "as_of": "2026-07-17",
        "canonical_version": VERSION if canonical is None else canonical,
        "burned_versions": BURNED_VERSIONS if burned is None else burned,
    }
    if distributable is not _ABSENT:
        data["distributable"] = distributable
    # Default: a distributable=true status carries a valid signer thumbprint (so
    # unrelated-axis overrides pass the schema). Pass None to omit it, or a value.
    if expected_signer_thumbprint is _UNSET:
        if distributable is True:
            data["expected_signer_thumbprint"] = SIGNER_THUMBPRINT
    elif expected_signer_thumbprint is not None:
        data["expected_signer_thumbprint"] = expected_signer_thumbprint
    if not drop_frozen:
        default_frozen = [{"name": "old.exe", "sha256": FROZEN_RC2_SHA, "why": "dnd"}]
        data["frozen_artifacts"] = default_frozen if frozen is None else frozen
    (repo / "release-status.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
    )


class _Absent:
    pass


_ABSENT = _Absent()  # sentinel: ключ distributable отсутствует


def mk_dist(repo: Path, version: str, exe_bytes: bytes = b"fresh-exe",
            bin_bytes: tuple[bytes, ...] = (b"bin1", b"bin2", b"bin3")) -> Path:
    """dist_premium/installer/ с exe + непрерывными .bin слайсами."""
    dist = repo / "dist_premium" / "installer"
    dist.mkdir(parents=True, exist_ok=True)
    (dist / f"KALI-Premium-Setup-{version}.exe").write_bytes(exe_bytes)
    for i, data in enumerate(bin_bytes, start=1):
        (dist / f"KALI-Premium-Setup-{version}-{i}.bin").write_bytes(data)
    # H6-5: a real installer build always seals the exact artifact list; publish reads
    # that manifest instead of globbing, so the fixture must model it.
    from scripts.release import installer_gate
    installer_gate.write_installer_manifest(dist, f"KALI-Premium-Setup-{version}.exe")
    return dist


def dist_assets(dist: Path, version: str) -> list[Path]:
    exe = dist / f"KALI-Premium-Setup-{version}.exe"
    bins = sorted(dist.glob(f"KALI-Premium-Setup-{version}-*.bin"))
    return [exe, *bins]


def write_manifest(dist: Path, version: str, git_sha: str, dirty: bool,
                   assets: list[Path], mobile_version: str = "0.1.0+1",
                   asset_sha_override: dict | None = None,
                   raw_drop: bool = False) -> None:
    """release-manifest.json, потребляемый guard (version/git_sha/dirty/assets)."""
    if raw_drop:
        return  # манифест намеренно отсутствует
    override = asset_sha_override or {}
    manifest = {
        "version": version,
        "git_sha": git_sha,
        "git_sha_short": git_sha[:12],
        "dirty": dirty,
        "components": {
            "pyproject": version, "kernel": version, "cargo_toml": version,
            "cargo_lock": version, "tauri": version, "iss": version,
            "ui": version, "mobile": mobile_version,
        },
        "generated_at": "2026-07-17T00:00:00+00:00",
        "assets": [
            {
                "name": a.name,
                "sha256": override.get(a.name, sha256_file(a)),
                "size": a.stat().st_size,
            }
            for a in assets
        ],
    }
    (dist / "release-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def set_asset_mtime(dist: Path, version: str, mtime: float) -> None:
    for a in dist_assets(dist, version):
        os.utime(a, (mtime, mtime))
